### ISSUE TITLE
Stating that GeoJSON can do non-WGS84 isn't accurate

### ISSUE THREAD

**Issue by pepijnve** [OpenGeoLabs/shapefilemustdie#17]
The spec is pretty clear that all GeoJSON is WGS-84. Using coordinates in any other CRS isn't going to be very interoperable. See https://tools.ietf.org/html/rfc7946#section-4.

**Comment by jachym** [comment]
Hm,  yes, it can. In my original version it was noted, that this is possible, will review.

**Comment by pepijnve** [comment]
The IETF spec refers to this as well and states that this capability has been intentionally removed. I remember discussing exactly this topic back when we were doing geopackage 1.0. Someone from the SWG reached out to the geo json guys about this and IIRC they were not interested in restoring this.

You can still do this anyway of course in the sense that you can store coordinates in whichever crs you like in a json file. But the geo json spec states clearly that the implicit crs is wgs84. The spec doesn’t provide any mechanism to encode a crs along with the coordinates. You can add a prj sidecar file for instance or use some other out of band mechanism (e.g. serve via WFS) but then you no longer have a stand-alone file and it’s not spec compliant.

**Comment by pepijnve** [comment]
Did some more research on this. Things changed quite a bit over time. The [original 2008 spec allowed](https://web.archive.org/web/20080730022240/http://geojson.org:80/geojson-spec.html#coordinate-reference-system-objects) it, early IETF drafts did as well, then [it got discouraged](https://sgillies.net/2014/08/06/pruning-crs-from-geojson.html) and [finally it was dropped](https://tools.ietf.org/html/rfc7946#appendix-B).

**Comment by pepijnve** [comment]
Did some more research on this. Things changed quite a bit over time. The [original 2008 spec allowed](https://web.archive.org/web/20080730022240/http://geojson.org:80/geojson-spec.html#coordinate-reference-system-objects) it, early IETF drafts did as well, then [it got discouraged](https://sgillies.net/2014/08/06/pruning-crs-from-geojson.html) and [finally it](https://sgillies.net/2016/08/11/rfc-7946-the-geojson-format.html#changes) [was dropped](https://tools.ietf.org/html/rfc7946#appendix-B).
