### ISSUE TITLE
Remove ESRI GeoDatabase

### ISSUE THREAD

**Issue by kannes** [OpenGeoLabs/shapefilemustdie#7]
It is hard to take this website seriously if it recommends ESRI GeoDatabase. As it says itself, that is a "proprietary, closed format"...

**Comment by jachym** [comment]
It's just discussed. Would new section "worth mentioning" be ok?

**Comment by mprins** [comment]
You ]would need to limit to FGDB, which is a collection of files

**Comment by jyutzler** [comment]
I personally believe that relegating FGDB to the bottom of the page is reasonable. How about you @kannes?

**Comment by kannes** [comment]
I cannot judge FGDB as I never use it myself. But I see no good reason to suggest switching to a "proprieray, closed" format.

**Comment by jachym** [comment]
looking good?
